/******************************************************************************
*  Generated by PSoC Designer ver 4.4  b1884 : 14 Jan, 2007
******************************************************************************/
#include <m8c.h>
// _ address and mask defines
#pragma	ioport	__Data_ADDR:	0x0
BYTE			__Data_ADDR;
#pragma	ioport	__DriveMode_0_ADDR:	0x100
BYTE			__DriveMode_0_ADDR;
#pragma	ioport	__DriveMode_1_ADDR:	0x101
BYTE			__DriveMode_1_ADDR;
#pragma	ioport	__DriveMode_2_ADDR:	0x3
BYTE			__DriveMode_2_ADDR;
#pragma	ioport	__GlobalSelect_ADDR:	0x2
BYTE			__GlobalSelect_ADDR;
#pragma	ioport	__IntCtrl_0_ADDR:	0x102
BYTE			__IntCtrl_0_ADDR;
#pragma	ioport	__IntCtrl_1_ADDR:	0x103
BYTE			__IntCtrl_1_ADDR;
#pragma	ioport	__IntEn_ADDR:	0x1
BYTE			__IntEn_ADDR;
#define __MASK 0x1
// LCD_Retroalimentacion address and mask defines
#pragma	ioport	LCD_Retroalimentacion_Data_ADDR:	0x0
BYTE			LCD_Retroalimentacion_Data_ADDR;
#pragma	ioport	LCD_Retroalimentacion_DriveMode_0_ADDR:	0x100
BYTE			LCD_Retroalimentacion_DriveMode_0_ADDR;
#pragma	ioport	LCD_Retroalimentacion_DriveMode_1_ADDR:	0x101
BYTE			LCD_Retroalimentacion_DriveMode_1_ADDR;
#pragma	ioport	LCD_Retroalimentacion_DriveMode_2_ADDR:	0x3
BYTE			LCD_Retroalimentacion_DriveMode_2_ADDR;
#pragma	ioport	LCD_Retroalimentacion_GlobalSelect_ADDR:	0x2
BYTE			LCD_Retroalimentacion_GlobalSelect_ADDR;
#pragma	ioport	LCD_Retroalimentacion_IntCtrl_0_ADDR:	0x102
BYTE			LCD_Retroalimentacion_IntCtrl_0_ADDR;
#pragma	ioport	LCD_Retroalimentacion_IntCtrl_1_ADDR:	0x103
BYTE			LCD_Retroalimentacion_IntCtrl_1_ADDR;
#pragma	ioport	LCD_Retroalimentacion_IntEn_ADDR:	0x1
BYTE			LCD_Retroalimentacion_IntEn_ADDR;
#define LCD_Retroalimentacion_MASK 0x2
// Reset_PSOCdT address and mask defines
#pragma	ioport	Reset_PSOCdT_Data_ADDR:	0x0
BYTE			Reset_PSOCdT_Data_ADDR;
#pragma	ioport	Reset_PSOCdT_DriveMode_0_ADDR:	0x100
BYTE			Reset_PSOCdT_DriveMode_0_ADDR;
#pragma	ioport	Reset_PSOCdT_DriveMode_1_ADDR:	0x101
BYTE			Reset_PSOCdT_DriveMode_1_ADDR;
#pragma	ioport	Reset_PSOCdT_DriveMode_2_ADDR:	0x3
BYTE			Reset_PSOCdT_DriveMode_2_ADDR;
#pragma	ioport	Reset_PSOCdT_GlobalSelect_ADDR:	0x2
BYTE			Reset_PSOCdT_GlobalSelect_ADDR;
#pragma	ioport	Reset_PSOCdT_IntCtrl_0_ADDR:	0x102
BYTE			Reset_PSOCdT_IntCtrl_0_ADDR;
#pragma	ioport	Reset_PSOCdT_IntCtrl_1_ADDR:	0x103
BYTE			Reset_PSOCdT_IntCtrl_1_ADDR;
#pragma	ioport	Reset_PSOCdT_IntEn_ADDR:	0x1
BYTE			Reset_PSOCdT_IntEn_ADDR;
#define Reset_PSOCdT_MASK 0x4
// Buzzer address and mask defines
#pragma	ioport	Buzzer_Data_ADDR:	0x0
BYTE			Buzzer_Data_ADDR;
#pragma	ioport	Buzzer_DriveMode_0_ADDR:	0x100
BYTE			Buzzer_DriveMode_0_ADDR;
#pragma	ioport	Buzzer_DriveMode_1_ADDR:	0x101
BYTE			Buzzer_DriveMode_1_ADDR;
#pragma	ioport	Buzzer_DriveMode_2_ADDR:	0x3
BYTE			Buzzer_DriveMode_2_ADDR;
#pragma	ioport	Buzzer_GlobalSelect_ADDR:	0x2
BYTE			Buzzer_GlobalSelect_ADDR;
#pragma	ioport	Buzzer_IntCtrl_0_ADDR:	0x102
BYTE			Buzzer_IntCtrl_0_ADDR;
#pragma	ioport	Buzzer_IntCtrl_1_ADDR:	0x103
BYTE			Buzzer_IntCtrl_1_ADDR;
#pragma	ioport	Buzzer_IntEn_ADDR:	0x1
BYTE			Buzzer_IntEn_ADDR;
#define Buzzer_MASK 0x8
// LED_Alimentacion address and mask defines
#pragma	ioport	LED_Alimentacion_Data_ADDR:	0x0
BYTE			LED_Alimentacion_Data_ADDR;
#pragma	ioport	LED_Alimentacion_DriveMode_0_ADDR:	0x100
BYTE			LED_Alimentacion_DriveMode_0_ADDR;
#pragma	ioport	LED_Alimentacion_DriveMode_1_ADDR:	0x101
BYTE			LED_Alimentacion_DriveMode_1_ADDR;
#pragma	ioport	LED_Alimentacion_DriveMode_2_ADDR:	0x3
BYTE			LED_Alimentacion_DriveMode_2_ADDR;
#pragma	ioport	LED_Alimentacion_GlobalSelect_ADDR:	0x2
BYTE			LED_Alimentacion_GlobalSelect_ADDR;
#pragma	ioport	LED_Alimentacion_IntCtrl_0_ADDR:	0x102
BYTE			LED_Alimentacion_IntCtrl_0_ADDR;
#pragma	ioport	LED_Alimentacion_IntCtrl_1_ADDR:	0x103
BYTE			LED_Alimentacion_IntCtrl_1_ADDR;
#pragma	ioport	LED_Alimentacion_IntEn_ADDR:	0x1
BYTE			LED_Alimentacion_IntEn_ADDR;
#define LED_Alimentacion_MASK 0x10
// Boton_rojo address and mask defines
#pragma	ioport	Boton_rojo_Data_ADDR:	0x0
BYTE			Boton_rojo_Data_ADDR;
#pragma	ioport	Boton_rojo_DriveMode_0_ADDR:	0x100
BYTE			Boton_rojo_DriveMode_0_ADDR;
#pragma	ioport	Boton_rojo_DriveMode_1_ADDR:	0x101
BYTE			Boton_rojo_DriveMode_1_ADDR;
#pragma	ioport	Boton_rojo_DriveMode_2_ADDR:	0x3
BYTE			Boton_rojo_DriveMode_2_ADDR;
#pragma	ioport	Boton_rojo_GlobalSelect_ADDR:	0x2
BYTE			Boton_rojo_GlobalSelect_ADDR;
#pragma	ioport	Boton_rojo_IntCtrl_0_ADDR:	0x102
BYTE			Boton_rojo_IntCtrl_0_ADDR;
#pragma	ioport	Boton_rojo_IntCtrl_1_ADDR:	0x103
BYTE			Boton_rojo_IntCtrl_1_ADDR;
#pragma	ioport	Boton_rojo_IntEn_ADDR:	0x1
BYTE			Boton_rojo_IntEn_ADDR;
#define Boton_rojo_MASK 0x20
// Boton_amarillo address and mask defines
#pragma	ioport	Boton_amarillo_Data_ADDR:	0x0
BYTE			Boton_amarillo_Data_ADDR;
#pragma	ioport	Boton_amarillo_DriveMode_0_ADDR:	0x100
BYTE			Boton_amarillo_DriveMode_0_ADDR;
#pragma	ioport	Boton_amarillo_DriveMode_1_ADDR:	0x101
BYTE			Boton_amarillo_DriveMode_1_ADDR;
#pragma	ioport	Boton_amarillo_DriveMode_2_ADDR:	0x3
BYTE			Boton_amarillo_DriveMode_2_ADDR;
#pragma	ioport	Boton_amarillo_GlobalSelect_ADDR:	0x2
BYTE			Boton_amarillo_GlobalSelect_ADDR;
#pragma	ioport	Boton_amarillo_IntCtrl_0_ADDR:	0x102
BYTE			Boton_amarillo_IntCtrl_0_ADDR;
#pragma	ioport	Boton_amarillo_IntCtrl_1_ADDR:	0x103
BYTE			Boton_amarillo_IntCtrl_1_ADDR;
#pragma	ioport	Boton_amarillo_IntEn_ADDR:	0x1
BYTE			Boton_amarillo_IntEn_ADDR;
#define Boton_amarillo_MASK 0x80
// UART_TX address and mask defines
#pragma	ioport	UART_TX_Data_ADDR:	0x4
BYTE			UART_TX_Data_ADDR;
#pragma	ioport	UART_TX_DriveMode_0_ADDR:	0x104
BYTE			UART_TX_DriveMode_0_ADDR;
#pragma	ioport	UART_TX_DriveMode_1_ADDR:	0x105
BYTE			UART_TX_DriveMode_1_ADDR;
#pragma	ioport	UART_TX_DriveMode_2_ADDR:	0x7
BYTE			UART_TX_DriveMode_2_ADDR;
#pragma	ioport	UART_TX_GlobalSelect_ADDR:	0x6
BYTE			UART_TX_GlobalSelect_ADDR;
#pragma	ioport	UART_TX_IntCtrl_0_ADDR:	0x106
BYTE			UART_TX_IntCtrl_0_ADDR;
#pragma	ioport	UART_TX_IntCtrl_1_ADDR:	0x107
BYTE			UART_TX_IntCtrl_1_ADDR;
#pragma	ioport	UART_TX_IntEn_ADDR:	0x5
BYTE			UART_TX_IntEn_ADDR;
#define UART_TX_MASK 0x10
// UART_RX address and mask defines
#pragma	ioport	UART_RX_Data_ADDR:	0x4
BYTE			UART_RX_Data_ADDR;
#pragma	ioport	UART_RX_DriveMode_0_ADDR:	0x104
BYTE			UART_RX_DriveMode_0_ADDR;
#pragma	ioport	UART_RX_DriveMode_1_ADDR:	0x105
BYTE			UART_RX_DriveMode_1_ADDR;
#pragma	ioport	UART_RX_DriveMode_2_ADDR:	0x7
BYTE			UART_RX_DriveMode_2_ADDR;
#pragma	ioport	UART_RX_GlobalSelect_ADDR:	0x6
BYTE			UART_RX_GlobalSelect_ADDR;
#pragma	ioport	UART_RX_IntCtrl_0_ADDR:	0x106
BYTE			UART_RX_IntCtrl_0_ADDR;
#pragma	ioport	UART_RX_IntCtrl_1_ADDR:	0x107
BYTE			UART_RX_IntCtrl_1_ADDR;
#pragma	ioport	UART_RX_IntEn_ADDR:	0x5
BYTE			UART_RX_IntEn_ADDR;
#define UART_RX_MASK 0x40
// LCDD4 address and mask defines
#pragma	ioport	LCDD4_Data_ADDR:	0x8
BYTE			LCDD4_Data_ADDR;
#pragma	ioport	LCDD4_DriveMode_0_ADDR:	0x108
BYTE			LCDD4_DriveMode_0_ADDR;
#pragma	ioport	LCDD4_DriveMode_1_ADDR:	0x109
BYTE			LCDD4_DriveMode_1_ADDR;
#pragma	ioport	LCDD4_DriveMode_2_ADDR:	0xb
BYTE			LCDD4_DriveMode_2_ADDR;
#pragma	ioport	LCDD4_GlobalSelect_ADDR:	0xa
BYTE			LCDD4_GlobalSelect_ADDR;
#pragma	ioport	LCDD4_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD4_IntCtrl_0_ADDR;
#pragma	ioport	LCDD4_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD4_IntCtrl_1_ADDR;
#pragma	ioport	LCDD4_IntEn_ADDR:	0x9
BYTE			LCDD4_IntEn_ADDR;
#define LCDD4_MASK 0x1
// LCDD4 Shadow defines
//   LCDD4_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD4_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD4_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD4_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD4_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD4_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD5 address and mask defines
#pragma	ioport	LCDD5_Data_ADDR:	0x8
BYTE			LCDD5_Data_ADDR;
#pragma	ioport	LCDD5_DriveMode_0_ADDR:	0x108
BYTE			LCDD5_DriveMode_0_ADDR;
#pragma	ioport	LCDD5_DriveMode_1_ADDR:	0x109
BYTE			LCDD5_DriveMode_1_ADDR;
#pragma	ioport	LCDD5_DriveMode_2_ADDR:	0xb
BYTE			LCDD5_DriveMode_2_ADDR;
#pragma	ioport	LCDD5_GlobalSelect_ADDR:	0xa
BYTE			LCDD5_GlobalSelect_ADDR;
#pragma	ioport	LCDD5_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD5_IntCtrl_0_ADDR;
#pragma	ioport	LCDD5_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD5_IntCtrl_1_ADDR;
#pragma	ioport	LCDD5_IntEn_ADDR:	0x9
BYTE			LCDD5_IntEn_ADDR;
#define LCDD5_MASK 0x2
// LCDD5 Shadow defines
//   LCDD5_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD5_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD5_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD5_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD5_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD5_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD6 address and mask defines
#pragma	ioport	LCDD6_Data_ADDR:	0x8
BYTE			LCDD6_Data_ADDR;
#pragma	ioport	LCDD6_DriveMode_0_ADDR:	0x108
BYTE			LCDD6_DriveMode_0_ADDR;
#pragma	ioport	LCDD6_DriveMode_1_ADDR:	0x109
BYTE			LCDD6_DriveMode_1_ADDR;
#pragma	ioport	LCDD6_DriveMode_2_ADDR:	0xb
BYTE			LCDD6_DriveMode_2_ADDR;
#pragma	ioport	LCDD6_GlobalSelect_ADDR:	0xa
BYTE			LCDD6_GlobalSelect_ADDR;
#pragma	ioport	LCDD6_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD6_IntCtrl_0_ADDR;
#pragma	ioport	LCDD6_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD6_IntCtrl_1_ADDR;
#pragma	ioport	LCDD6_IntEn_ADDR:	0x9
BYTE			LCDD6_IntEn_ADDR;
#define LCDD6_MASK 0x4
// LCDD6 Shadow defines
//   LCDD6_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD6_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD6_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD6_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD6_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD6_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDD7 address and mask defines
#pragma	ioport	LCDD7_Data_ADDR:	0x8
BYTE			LCDD7_Data_ADDR;
#pragma	ioport	LCDD7_DriveMode_0_ADDR:	0x108
BYTE			LCDD7_DriveMode_0_ADDR;
#pragma	ioport	LCDD7_DriveMode_1_ADDR:	0x109
BYTE			LCDD7_DriveMode_1_ADDR;
#pragma	ioport	LCDD7_DriveMode_2_ADDR:	0xb
BYTE			LCDD7_DriveMode_2_ADDR;
#pragma	ioport	LCDD7_GlobalSelect_ADDR:	0xa
BYTE			LCDD7_GlobalSelect_ADDR;
#pragma	ioport	LCDD7_IntCtrl_0_ADDR:	0x10a
BYTE			LCDD7_IntCtrl_0_ADDR;
#pragma	ioport	LCDD7_IntCtrl_1_ADDR:	0x10b
BYTE			LCDD7_IntCtrl_1_ADDR;
#pragma	ioport	LCDD7_IntEn_ADDR:	0x9
BYTE			LCDD7_IntEn_ADDR;
#define LCDD7_MASK 0x8
// LCDD7 Shadow defines
//   LCDD7_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDD7_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDD7_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDD7_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDD7_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDD7_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDE address and mask defines
#pragma	ioport	LCDE_Data_ADDR:	0x8
BYTE			LCDE_Data_ADDR;
#pragma	ioport	LCDE_DriveMode_0_ADDR:	0x108
BYTE			LCDE_DriveMode_0_ADDR;
#pragma	ioport	LCDE_DriveMode_1_ADDR:	0x109
BYTE			LCDE_DriveMode_1_ADDR;
#pragma	ioport	LCDE_DriveMode_2_ADDR:	0xb
BYTE			LCDE_DriveMode_2_ADDR;
#pragma	ioport	LCDE_GlobalSelect_ADDR:	0xa
BYTE			LCDE_GlobalSelect_ADDR;
#pragma	ioport	LCDE_IntCtrl_0_ADDR:	0x10a
BYTE			LCDE_IntCtrl_0_ADDR;
#pragma	ioport	LCDE_IntCtrl_1_ADDR:	0x10b
BYTE			LCDE_IntCtrl_1_ADDR;
#pragma	ioport	LCDE_IntEn_ADDR:	0x9
BYTE			LCDE_IntEn_ADDR;
#define LCDE_MASK 0x10
// LCDE Shadow defines
//   LCDE_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDE_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDE_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDE_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDE_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDE_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDRS address and mask defines
#pragma	ioport	LCDRS_Data_ADDR:	0x8
BYTE			LCDRS_Data_ADDR;
#pragma	ioport	LCDRS_DriveMode_0_ADDR:	0x108
BYTE			LCDRS_DriveMode_0_ADDR;
#pragma	ioport	LCDRS_DriveMode_1_ADDR:	0x109
BYTE			LCDRS_DriveMode_1_ADDR;
#pragma	ioport	LCDRS_DriveMode_2_ADDR:	0xb
BYTE			LCDRS_DriveMode_2_ADDR;
#pragma	ioport	LCDRS_GlobalSelect_ADDR:	0xa
BYTE			LCDRS_GlobalSelect_ADDR;
#pragma	ioport	LCDRS_IntCtrl_0_ADDR:	0x10a
BYTE			LCDRS_IntCtrl_0_ADDR;
#pragma	ioport	LCDRS_IntCtrl_1_ADDR:	0x10b
BYTE			LCDRS_IntCtrl_1_ADDR;
#pragma	ioport	LCDRS_IntEn_ADDR:	0x9
BYTE			LCDRS_IntEn_ADDR;
#define LCDRS_MASK 0x20
// LCDRS Shadow defines
//   LCDRS_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDRS_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDRS_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDRS_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDRS_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDRS_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
// LCDRW address and mask defines
#pragma	ioport	LCDRW_Data_ADDR:	0x8
BYTE			LCDRW_Data_ADDR;
#pragma	ioport	LCDRW_DriveMode_0_ADDR:	0x108
BYTE			LCDRW_DriveMode_0_ADDR;
#pragma	ioport	LCDRW_DriveMode_1_ADDR:	0x109
BYTE			LCDRW_DriveMode_1_ADDR;
#pragma	ioport	LCDRW_DriveMode_2_ADDR:	0xb
BYTE			LCDRW_DriveMode_2_ADDR;
#pragma	ioport	LCDRW_GlobalSelect_ADDR:	0xa
BYTE			LCDRW_GlobalSelect_ADDR;
#pragma	ioport	LCDRW_IntCtrl_0_ADDR:	0x10a
BYTE			LCDRW_IntCtrl_0_ADDR;
#pragma	ioport	LCDRW_IntCtrl_1_ADDR:	0x10b
BYTE			LCDRW_IntCtrl_1_ADDR;
#pragma	ioport	LCDRW_IntEn_ADDR:	0x9
BYTE			LCDRW_IntEn_ADDR;
#define LCDRW_MASK 0x40
// LCDRW Shadow defines
//   LCDRW_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LCDRW_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
//   LCDRW_DriveMode_0Shadow define
extern BYTE Port_2_DriveMode_0_SHADE;
#define LCDRW_DriveMode_0Shadow (*(unsigned char*)&Port_2_DriveMode_0_SHADE)
//   LCDRW_DriveMode_1Shadow define
extern BYTE Port_2_DriveMode_1_SHADE;
#define LCDRW_DriveMode_1Shadow (*(unsigned char*)&Port_2_DriveMode_1_SHADE)
