//*****************************************************************************
//*****************************************************************************
//  FILENAME: Segundos.h
//   Version: 2.5, Updated on 2006/06/19 at 11:17:22
//  Generated by PSoC Designer ver 4.4  b1884 : 14 Jan, 2007
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//               for the 22/24/27/29xxx PSoC family of devices
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress MicroSystems 2000-2004. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 Segundos_EnableInt
#pragma fastcall16 Segundos_DisableInt
#pragma fastcall16 Segundos_Start
#pragma fastcall16 Segundos_Stop
#pragma fastcall16 Segundos_wReadTimer                // Read  DR0
#pragma fastcall16 Segundos_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 Segundos_WritePeriod               // Write DR1
#pragma fastcall16 Segundos_wReadCompareValue         // Read  DR2
#pragma fastcall16 Segundos_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wSegundos_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wSegundos_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wSegundos_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wSegundos_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wSegundos_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the Segundos API.
//-------------------------------------------------

extern void Segundos_EnableInt(void);                           // Proxy 1
extern void Segundos_DisableInt(void);                          // Proxy 1
extern void Segundos_Start(void);                               // Proxy 1
extern void Segundos_Stop(void);                                // Proxy 1
extern WORD Segundos_wReadTimer(void);                          // Proxy 1
extern WORD Segundos_wReadTimerSaveCV(void);                    // Proxy 2
extern void Segundos_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD Segundos_wReadCompareValue(void);                   // Proxy 1
extern void Segundos_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wSegundos_ReadCompareValue(void);       // Deprecated
extern WORD wSegundos_ReadTimerSaveCV(void);        // Deprecated
extern WORD wSegundos_ReadCounter(void);            // Obsolete
extern WORD wSegundos_ReadTimer(void);              // Deprecated
extern WORD wSegundos_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for Segundos API's.
//--------------------------------------------------

#define Segundos_CONTROL_REG_START_BIT         ( 0x01 )
#define Segundos_INT_REG_ADDR                  ( 0x0e1 )
#define Segundos_INT_MASK                      ( 0x20 )


//--------------------------------------------------
// Constants for Segundos user defined values
//--------------------------------------------------

#define Segundos_PERIOD                        ( 0x0 )
#define Segundos_COMPARE_VALUE                 ( 0x0 )


//-------------------------------------------------
// Register Addresses for Segundos
//-------------------------------------------------

#pragma ioport  Segundos_COUNTER_LSB_REG:   0x030          //Count register LSB
BYTE            Segundos_COUNTER_LSB_REG;
#pragma ioport  Segundos_COUNTER_MSB_REG:   0x034          //Count register MSB
BYTE            Segundos_COUNTER_MSB_REG;
#pragma ioport  Segundos_PERIOD_LSB_REG:    0x031          //Period register LSB
BYTE            Segundos_PERIOD_LSB_REG;
#pragma ioport  Segundos_PERIOD_MSB_REG:    0x035          //Period register MSB
BYTE            Segundos_PERIOD_MSB_REG;
#pragma ioport  Segundos_COMPARE_LSB_REG:   0x032          //Compare register LSB
BYTE            Segundos_COMPARE_LSB_REG;
#pragma ioport  Segundos_COMPARE_MSB_REG:   0x036          //Compare register MSB
BYTE            Segundos_COMPARE_MSB_REG;
#pragma ioport  Segundos_CONTROL_LSB_REG:   0x033          //Control register LSB
BYTE            Segundos_CONTROL_LSB_REG;
#pragma ioport  Segundos_CONTROL_MSB_REG:   0x037          //Control register MSB
BYTE            Segundos_CONTROL_MSB_REG;
#pragma ioport  Segundos_FUNC_LSB_REG:  0x130              //Function register LSB
BYTE            Segundos_FUNC_LSB_REG;
#pragma ioport  Segundos_FUNC_MSB_REG:  0x134              //Function register MSB
BYTE            Segundos_FUNC_MSB_REG;
#pragma ioport  Segundos_INPUT_LSB_REG: 0x131              //Input register LSB
BYTE            Segundos_INPUT_LSB_REG;
#pragma ioport  Segundos_INPUT_MSB_REG: 0x135              //Input register MSB
BYTE            Segundos_INPUT_MSB_REG;
#pragma ioport  Segundos_OUTPUT_LSB_REG:    0x132          //Output register LSB
BYTE            Segundos_OUTPUT_LSB_REG;
#pragma ioport  Segundos_OUTPUT_MSB_REG:    0x136          //Output register MSB
BYTE            Segundos_OUTPUT_MSB_REG;
#pragma ioport  Segundos_INT_REG:       0x0e1              //Interrupt Mask Register
BYTE            Segundos_INT_REG;


//-------------------------------------------------
// Segundos Macro 'Functions'
//-------------------------------------------------

#define Segundos_Start_M \
   ( Segundos_CONTROL_LSB_REG |=  Segundos_CONTROL_REG_START_BIT )

#define Segundos_Stop_M  \
   ( Segundos_CONTROL_LSB_REG &= ~Segundos_CONTROL_REG_START_BIT )

#define Segundos_EnableInt_M   \
   M8C_EnableIntMask(  Segundos_INT_REG, Segundos_INT_MASK )

#define Segundos_DisableInt_M  \
   M8C_DisableIntMask( Segundos_INT_REG, Segundos_INT_MASK )


// end of file Segundos.h


